<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVBz8oqi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVBz8oqi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVBz8oqi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVBz8oqi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVBz8oqi\App_KernelDevDebugContainer([
    'container.build_hash' => 'VBz8oqi',
    'container.build_id' => '359404d1',
    'container.build_time' => 1589653750,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVBz8oqi');
