<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU3cJBvD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU3cJBvD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU3cJBvD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU3cJBvD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU3cJBvD\App_KernelDevDebugContainer([
    'container.build_hash' => 'U3cJBvD',
    'container.build_id' => 'da11630a',
    'container.build_time' => 1592904871,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU3cJBvD');
